# -*- coding: utf-8 -*-
"""bootstrap_mediation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10d1TW1ccbRMlHR6jIsCYc9c3L6Rt8eBi
"""

import numpy as np
import pandas as pd
import statsmodels.api as sm
from sklearn.utils import resample

df = pd.read_csv("Germany_MODIS_Resistance_ZonalStats_2017_2024_NO_CALENDAR.csv")

def indirect_effect(data):
    X = data["summer_temp_anomaly"].values
    M = data["summer_sm_anomaly"].values
    Y = data["anomaly_growing_mean_ndvi"].values

    model_a = sm.OLS(M, sm.add_constant(X)).fit()
    a = model_a.params[1]

    XM = sm.add_constant(np.column_stack([X, M]))
    model_b = sm.OLS(Y, XM).fit()
    b = model_b.params[2]

    return a * b

boot_results = []
for i in range(1000):
    sample = df.sample(n=len(df), replace=True)
    boot_results.append(indirect_effect(sample))

boot_results = np.array(boot_results)

indirect = np.mean(boot_results)
ci_lower = np.percentile(boot_results, 2.5)
ci_upper = np.percentile(boot_results, 97.5)

print("Indirect effect:", indirect)
print("95% CI:", ci_lower, ci_upper)