# -*- coding: utf-8 -*-
"""morans-Iiipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10d1TW1ccbRMlHR6jIsCYc9c3L6Rt8eBi
"""

import pandas as pd
import numpy as np
import statsmodels.api as sm
from esda.moran import Moran
from libpysal.weights import KNN

df = pd.read_csv("Germany_MODIS_Resistance_ZonalStats_2017_2024_NO_CALENDAR.csv")

# Almanya eyaletleri için yaklaşık koordinatlar
coords_dict = {
    'Baden-Württemberg': (48.6616, 9.3501),
    'Bavaria': (48.7904, 11.4979),
    'Berlin': (52.5200, 13.4050),
    'Brandenburg': (52.4125, 12.5316),
    'Bremen': (53.0793, 8.8017),
    'Hamburg': (53.5753, 10.0153),
    'Hesse': (50.6521, 9.1624),
    'Mecklenburg-Vorpommern': (53.6127, 12.4296),
    'Lower Saxony': (52.6367, 9.8451),
    'North Rhine-Westphalia': (51.4332, 7.6616),
    'Rhineland-Palatinate': (50.1183, 7.3089),
    'Saarland': (49.3964, 7.0228),
    'Saxony': (51.1045, 13.2017),
    'Saxony-Anhalt': (51.9503, 11.6923),
    'Schleswig-Holstein': (54.2194, 9.6961),
    'Thuringia': (50.9153, 11.0686),
}

print("CSV'deki bölge isimleri:")
print(df['adm1_name'].unique())

import pandas as pd
import numpy as np
import statsmodels.api as sm
from esda.moran import Moran
from libpysal.weights import KNN
df = pd.read_csv("Germany_MODIS_Resistance_ZonalStats_2017_2024_NO_CALENDAR.csv")
coords_dict = {
    'Baden-Wuerttemberg': (48.6616, 9.3501),
    'Bayern': (48.7904, 11.4979),
    'Berlin': (52.5200, 13.4050),
    'Brandenburg': (52.4125, 12.5316),
    'Bremen': (53.0793, 8.8017),
    'Hamburg': (53.5753, 10.0153),
    'Hessen': (50.6521, 9.1624),
    'Mecklenburg-Vorpommern': (53.6127, 12.4296),
    'Niedersachsen': (52.6367, 9.8451),
    'Nordrhein-Westfalen': (51.4332, 7.6616),
    'Rheinland-Pfalz': (50.1183, 7.3089),
    'Saarland': (49.3964, 7.0228),
    'Sachsen': (51.1045, 13.2017),
    'Sachsen-Anhalt': (51.9503, 11.6923),
    'Schleswig-Holstein': (54.2194, 9.6961),
    'Thueringen': (50.9153, 11.0686),
    }
df['lat'] = df['adm1_name'].map(lambda x: coords_dict[x][0])
df['lon'] = df['adm1_name'].map(lambda x: coords_dict[x][1])

X = sm.add_constant(df[['summer_sm_anomaly', 'summer_temp_anomaly']])
Y = df['anomaly_growing_mean_ndvi']
model = sm.OLS(Y, X).fit()
residuals = model.resid

coords = df[['lon', 'lat']].values
w = KNN.from_array(coords, k=5)
w.transform = 'r'

moran_ndvi = Moran(df['anomaly_growing_mean_ndvi'], w)
print(f"Moran's I (NDVI anomaly): {moran_ndvi.I:.4f}, p = {moran_ndvi.p_sim:.4f}")

moran_resid = Moran(residuals, w)
print(f"Moran's I (residuals): {moran_resid.I:.4f}, p = {moran_resid.p_sim:.4f}")

for k in [3, 5, 8]:
    w = KNN.from_array(coords, k=k)
    w.transform = 'r'
    m = Moran(df['anomaly_growing_mean_ndvi'], w)
    print(f"k={k}: I={m.I:.3f}, p={m.p_sim:.3f}")